DEFAULT_CNA: 2
E: .01
SITE_COVERAGE_THRESHOLD: .66
CELL_COVERAGE_THRESHOLD: .66
STATUS_CONFIDENCE_THRESHOLD: 1 
P00: .33
P10: .33
P11: .33
P: .5
D0010: .5
D0011: 1
D1011: .5
MAX_ITER: 15
KAPPA: .1
PARTITION_VALIDITY_THRESHOLD: .5

PATIENTS:
    CRC01: 
        methylated_rc: /data/CDSLSahinalp/bian-colorectal/final_hopefully/CRC01_met_read_count_mat_uncorr.npz
        unmethylated_rc: /data/CDSLSahinalp/bian-colorectal/final_hopefully/CRC01_unmet_read_count_mat_uncorr.npz
        cna: /data/CDSLSahinalp/bian-colorectal/final_hopefully/CpG_CNA_calls.npz
        whitelist: /data/CDSLSahinalp/yuelin/CRC01_whitelist.txt
        root: NC_507
        labels: /data/CDSLSahinalp/yuelin/CRC01_labels.csv
        palette:
            lesion:
                NC: "#A7A7A7"
                LN: "#EF8432"
                PT: "#487DB2"
                ML: "#D1342B"
                MP: "#68AC57"
            sampling_location:
                NC: "#A7A7A7"
                LN1: "#F8CA98"
                LN2: "#F38419"
                PT1: "#AFD1F2"
                PT2: "#739CC5"
                PT3: "#42719F"
                PT4: "#205183"
                ML1: "#E8A9A8"
                ML2: "#CC3426"
                ML3: "#B94C47"
                ML4: "#89221B"
                MP1: "#DBF7D4"
                MP2: "#9EF185"
                MP3: "#4FB31A"
                MP4: "#489C22"
                MP5: "#32780D"
