CRC01: 
    methylated_rc: /data/CDSLSahinalp/bian-colorectal/131k_196cell_uncorrected_read/CRC01_met_read_count_mat.npz
    unmethylated_rc: /data/CDSLSahinalp/bian-colorectal/131k_196cell_uncorrected_read/CRC01_unmet_read_count_mat.npz
    cna: /data/CDSLSahinalp/bian-colorectal/CNA_call/131k_CNA_calls.npz 
